### ISSUE TITLE
good job

### ISSUE THREAD

**Issue by william10240** [LuizZak/GIFViewer#1]
I use this soft for two years ,when i updated windows to 10 yesterday,i can`t find the installation package,so i find it from web,then i find your name,then i try to search in github.

emmm,I just want to say "Good job,thank you".

**Comment by LuizZak** [comment]
Hey, you're very welcome! It's always nice to find out your project is being useful to someone. So thank you for the feedback!

I'll consider this issue closed, now! Cheers!
